### PR TITLE
Mod works on server without crashing

### LINKED ISSUE #30: Move Screen code to client entrypoint

### PR DESCRIPTION
**Pull request by kvverti**
Fixes #30

### CODE REVIEW

File: src/main/scala/robosky/ether/client/gui/GuiRegistry.scala [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+import robosky.ether.UplandsMod
+import robosky.ether.block.machine.infuser.InfuserContainer
+
+// delete this class?
+class InfuserScreen(container: InfuserContainer, player: PlayerEntity)
+  extends CottonScreen[InfuserContainer](container, player)
+
+object GuiRegistry {
+
+  val agisaltInfuserScreen = registerGui("aegisalt_infuser", new InfuserContainer(_, _, _), new InfuserScreen(_, _))
```
Comment (Khitiara) [inline src/main/scala/robosky/ether/client/gui/GuiRegistry.scala]: get the container creation from the machine registry code

**Review by Khitiara — CHANGES_REQUESTED** [review]
Note one comment, otherwise looks good to me 👍

File: src/main/scala/robosky/ether/client/gui/GuiRegistry.scala (hunk 1 above)
Comment (kvverti) [reply src/main/scala/robosky/ether/client/gui/GuiRegistry.scala]: Changed to retrieve the controller and the id from the machine entry

**Review by Khitiara — APPROVED** [review]
